version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ezemlyanskiy/taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static

  frontend:
    image: ezemlyanskiy/taski_frontend
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/

  gateway:
    image: ezemlyanskiy/taski_gateway
    volumes:
      - static:/staticfiles
    ports:
      - 8080:80
